export const COUNTRIES_API = 'https://restcountries.eu/rest/v1/all';
export const DECREASE = 'DECREASE';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const INCREASE = 'INCREASE';
export const RECEIVE_COUNTRIES= 'RECEIVE_COUNTRIES';
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const ADD_COUNTRY= 'ADD_COUNTRY';
export const REMOVE_COUNTRY= 'REMOVE_COUNTRY';
export const FILTER_COUNTRIES= 'FILTER_COUNTRIES';
